#cloud-config

# Update packages and install required software
package_update: true
package_upgrade: true

packages:
- zsh
- git
- curl
- wget
- lsd
- neovim

# Create user and set shell
users:
- name: zk
  groups: sudo
  shell: /usr/bin/zsh
  sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
  ssh_import_id:
  - gh:zachklingbeil

# Run commands after package installation
runcmd:
- chown -R zk:zk /home/zk

# Final message
final_message: |
  Server setup complete! 
  ZSH is now the default shell with your custom configuration.
  SSH keys are stored in ~/.config/ssh following XDG standards.
  All dotfiles have been installed from your repository.
  Log out and back in to use ZSH.
