services:
    registry:
        container_name: registry
        image: registry
        expose:
            - 5000
            - 5001
        volumes:
            - registry:/registry
            - ../hello_universe:/htpasswd
        networks:
            - timefactory
        labels:
            - traefik.enable=true
            - traefik.http.routers.registry.rule=Host(`registry.timefactory.io`)
            - traefik.http.routers.registry.entrypoints=websecure
            - traefik.http.routers.registry.tls=true
            - traefik.http.routers.registry.tls.certresolver=myresolver
            - traefik.http.services.registry.loadbalancer.server.port=5000
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            REGISTRY_AUTH_HTPASSWD_PATH: /htpasswd
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
            REGISTRY_STORAGE_DELETE_ENABLED: true
            OTEL_TRACES_EXPORTER: none
            REGISTRY_LOG_LEVEL: info
        restart: always
        pull_policy: always

networks:
    timefactory:
        external: true
volumes:
    registry:
        external: true
