name: Universal Build

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: [ self-hosted, linux, x64 ]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine tag type
      id: tagtype
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.0$ ]]; then
          echo "is_release=true" >> $GITHUB_OUTPUT
          echo "is_patch=false" >> $GITHUB_OUTPUT
        else
          echo "is_release=false" >> $GITHUB_OUTPUT
          echo "is_patch=true" >> $GITHUB_OUTPUT
        fi

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          docker.io/timefactory/${{ github.event.repository.name }}
          ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=dev,enable=${{ steps.tagtype.outputs.is_patch }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ steps.tagtype.outputs.is_release }}
          type=raw,value=latest,enable=${{ steps.tagtype.outputs.is_release }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
