services:
    geth:
        image: ethereum/client-go
        container_name: geth
        pull_policy: always
        volumes:
            - geth:/.ethereum
            - ./jwt.hex:/root/jwt.hex
            # openssl rand -hex 32 > jwt.hex
        networks:
            - timefactory
        ports:
            - 30303:30303
            - 30303:30303/udp
        expose:
            - 8545
            - 8546
            - 8551
        labels:
            - traefik.enable=true
            - traefik.http.routers.geth-http.rule=Host(`geth.timefactory.io`) && PathPrefix(`/`)
            - traefik.http.routers.geth-http.entrypoints=https
            - traefik.http.routers.geth-http.service=geth-http
            - traefik.http.services.geth-http.loadbalancer.server.port=8545

            - traefik.http.routers.geth-ws.rule=Host(`geth.timefactory.io`) && PathPrefix(`/ws`)
            - traefik.http.routers.geth-ws.entrypoints=https
            - traefik.http.routers.geth-ws.service=geth-ws
            - traefik.http.services.geth-ws.loadbalancer.server.port=8546
        command: >
            --ipcpath=/.ethereum/geth.ipc
            --authrpc.addr 0.0.0.0
            --authrpc.port 8551
            --authrpc.jwtsecret=/root/jwt.hex
            --authrpc.vhosts "*"
            --syncmode full
            --http
            --http.api eth,net,web3,txpool
            --http.corsdomain "*"
            --http.vhosts "*"
            --http.port 8545
            --http.addr 0.0.0.0
            --ws
            --ws.api eth,net,web3,txpool
            --ws.origins "*"
            --ws.port 8546
            --ws.addr 0.0.0.0
            --cache 12288
        #--history.state=0
        #--gcmode archive
        restart: unless-stopped

networks:
    timefactory:
        external: true
volumes:
    geth:
        external: true
