services:
    user-ops-indexer:
        image: ghcr.io/blockscout/user-ops-indexer
        container_name: user-ops-indexer
        pull_policy: always
        restart: always
        environment:
            - USER_OPS_INDEXER__INDEXER__RPC_URL=ws://geth:8546
            - USER_OPS_INDEXER__DATABASE__CONNECT__URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout
            - USER_OPS_INDEXER__DATABASE__RUN_MIGRATIONS=true
        depends_on:
            - backend
        networks:
            - timefactory
        expose:
            - 8050

networks:
    timefactory:
        external: true
