services:
    geth:
        image: ethereum/client-go
        container_name: geth
        pull_policy: always
        volumes:
            - geth:/.ethereum
            - ./jwt.hex:/root/jwt.hex
            # openssl rand -hex 32 > jwt.hex
        networks:
            - timefactory
        ports:
            - 30303:30303
            - 30303:30303/udp
            - 127.0.0.1:8545:8545
            - 127.0.0.1:8546:8546
        expose:
            - 8551
        command: >
            --mainnet
            --syncmode snap 
            --ipcpath=/.ethereum/geth.ipc
            --authrpc.addr 0.0.0.0
            --authrpc.port 8551
            --authrpc.jwtsecret=/root/jwt.hex
            --authrpc.vhosts "*"
            --http
            --http.api eth,net,web3,txpool,debug,admin
            --http.corsdomain "*"
            --http.vhosts "*"
            --http.port 8545
            --http.addr 0.0.0.0
            --ws
            --ws.api eth,net,web3,txpool,debug,admin
            --ws.origins "*"
            --ws.port 8546
            --ws.addr 0.0.0.0
            --cache 16384
        restart: unless-stopped

    lighthouse:
        image: sigp/lighthouse
        container_name: lighthouse
        pull_policy: always
        networks:
            - timefactory
        ports:
            - 9000:9000
            - 9000:9000/udp
            - 9001:9001/udp
        expose:
            - 5052
        volumes:
            - lighthouse:/.lighthouse
            - ./jwt.hex:/root/jwt.hex
        command: >
            lighthouse
            --network mainnet
            beacon
            --http
            --http-address 0.0.0.0
            --http-port 5052
            --execution-endpoint http://geth:8551
            --execution-jwt /root/jwt.hex
            --checkpoint-sync-url https://mainnet.checkpoint.sigp.io
            --disable-backfill-rate-limiting
        restart: unless-stopped
        depends_on:
            - geth
networks:
    timefactory:
        external: true
volumes:
    geth:
        external: true
    lighthouse:
        external: true
