services:
    factory:
        container_name: factory
        image: registry.timefactory.io/factory
        pull_policy: always
        restart: unless-stopped
        volumes:
            - ./atomic.json:/factory/atomic.json
        networks:
            - timefactory
        labels:
            - traefik.enable=true
            - traefik.http.routers.factory.rule=Host(`timefactory.io`)
            - traefik.http.routers.factory.entrypoints=websecure
            - traefik.http.routers.factory.tls=true
            - traefik.http.routers.factory.tls.certresolver=cloudflare
            - traefik.http.routers.factory.service=factory
            - traefik.http.services.factory.loadbalancer.server.port=1001
            # - traefik.http.routers.factory.middlewares=authentik@file

networks:
    timefactory:
        external: true
