services:
    ubuntu-server:
        image: ubuntu:22.04
        container_name: ubuntu-server
        command: sleep infinity
        networks:
            - timefactory
        expose:
            - 80
            - 8080
            - 8081
        volumes:
            - ubuntu:/data

networks:
    timefactory:
        external: true

volumes:
    ubuntu:
        external: true
