http:
  middlewares:
    security-headers:
      headers:
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        forceSTSHeader: true
        stsSeconds: 63072000
    apikey-auth:
      headers:
        customRequestHeaders:
          X-API-Key: "your-secret-key"
    auth:
      basic-auth:
        users:
        - "zk:$$2y$$05$$m6SVpV9mmFqw8v3RqhDogurmorPxUFsF3PM6DOivWreVXktOvRlN."

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
