services:
    traefik:
        image: traefik
        container_name: traefik
        restart: always
        ports:
            - 80:80/tcp # http
            - 443:443/tcp # https
            - 443:443/udp # https http3 quic
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik:/etc/traefik
            - ./traefik.yml:/etc/traefik/traefik.yml
        environment:
            - TZ=America/Los_Angeles
            - CF_DNS_API_TOKEN=${CF_API_KEY}
        labels:
            - traefik.enable=true
        security_opt:
            - no-new-privileges:true
        networks:
            - timefactory

networks:
    timefactory:
        external: true

volumes:
    traefik:
        external: true
