# Traefik global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Enable traefik ui dashboard
api:
  dashboard: true
  insecure: false

# Log level INFO|DEBUG|ERROR
log:
  level: INFO
accessLog: {}

# The setting below is to allow insecure backend connections.  
serverTransport:
  insecureSkipVerify: true

# Traefik entrypoints (network ports) configuration
entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: myresolver
        domains:
        - main: timefactory.io
          sans:
          - '*.timefactory.io'
providers:
  providersThrottleDuration: 2s
  file:
    filename: /traefik/config.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    watch: true
    network: timefactory
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.timefactory.io`)" # change 'example.com' to your proxy domain
    exposedByDefault: false

# Use letsencrypt to generate ssl certificates
certificatesResolvers:
  myresolver:
    acme:
      email: zach@zachklingbeil.com # the email address used for ssl certificate registration
      storage: /traefik/acme.json
      dnsChallenge:
        # acme dns challenge; requires api token of dns provider
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the right dns servers
        resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"
