global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

log:
  level: INFO
  # format: json

accessLog: {}

serverTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443
    http3:
      advertisedPort: 443

providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    network: timefactory
    endpoint: "unix:///var/run/docker.sock"
    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.timefactory.io`)"
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: zach@zachklingbeil.com
      storage: acme.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
