services:
    lighthouse:
        image: sigp/lighthouse
        container_name: lighthouse
        pull_policy: always
        networks:
            - timefactory
        ports:
            - 9000:9000
            - 9000:9000/udp
            - 9001:9001/udp
        expose:
            - 5052
        volumes:
            - lighthouse:/.lighthouse
            - ./jwt.hex:/root/jwt.hex
        command: >
            lighthouse
            --network mainnet
            beacon
            --http
            --http-address 0.0.0.0
            --http-port 5052
            --execution-endpoint http://geth:8551
            --execution-jwt /root/jwt.hex
            --checkpoint-sync-url https://mainnet.checkpoint.sigp.io
            --disable-backfill-rate-limiting
            --genesis-backfill
        restart: unless-stopped
networks:
    timefactory:
        external: true
volumes:
    lighthouse:
        external: true
