services:
    postgres:
        container_name: postgres
        image: postgres:alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - timefactory
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        command:
            [
                'postgres',
                '-c',
                'max_wal_size=8GB',
                '-c',
                'max_connections=200',
                '-c',
                'client_connection_check_interval=60000',
            ]

        restart: unless-stopped
        pull_policy: always

    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        environment:
            - REDIS_PASSWORD=${PASSWORD}
        command: redis-server --requirepass ${PASSWORD} --maxmemory 12GB --maxmemory-policy allkeys-lru
        # redis://:${PASSWORD}@redis:6379/<db>
        networks:
            - timefactory
        restart: unless-stopped
        pull_policy: always

networks:
    timefactory:
        external: true

volumes:
    postgres:
        external: true
    redis:
        external: true
