services:
    backend:
        image: registry.timefactory.io/indexer
        container_name: backend
        pull_policy: always
        restart: always
        stop_grace_period: 5m
        user: 0:0
        environment:
            - DATABASE_URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout?ssl=false
            - USER_OPS_INDEXER__DATABASE__CONNECT__URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout?ssl=false
            - REDIS_URL=redis://redis:6379/1
        networks:
            - timefactory
        expose:
            - 4000
        volumes:
            - blockscout:/app/logs/
            - blockscout:/app/dets/
            - ethereum:/.ethereum:ro

networks:
    timefactory:
        external: true
volumes:
    blockscout:
        external: true
    ethereum:
        external: true
