services:
    backend:
        image: ghcr.io/blockscout/blockscout
        container_name: backend
        pull_policy: always
        restart: always
        stop_grace_period: 5m
        command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
        environment:
            - DATABASE_URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout
            - REDIS_URL=redis://redis:6379/1
            - ETHEREUM_JSONRPC_HTTP_URL=http://geth:8545
            - ETHEREUM_JSONRPC_WS_URL=ws://geth:8546
            - CHAIN_ID=1
        networks:
            - timefactory
        expose:
            - 7999
        volumes:
            - blockscout:/app/logs/
            - blockscout:/app/dets/

    sig-provider:
        container_name: sig-provider
        image: ghcr.io/blockscout/sig-provider
        pull_policy: always
        restart: always
        networks:
            - timefactory
        expose:
            - 8050

    sc-verifier:
        image: ghcr.io/blockscout/smart-contract-verifier
        container_name: smart-contract-verifier
        pull_policy: always
        restart: always
        networks:
            - timefactory
        expose:
            - 8050

    user-ops-indexer:
        image: ghcr.io/blockscout/user-ops-indexer
        container_name: user-ops-indexer
        pull_policy: always
        restart: always
        environment:
            - USER_OPS_INDEXER__INDEXER__RPC_URL=${USER_OPS_INDEXER__INDEXER__RPC_URL:-ws://host.docker.internal:8545/}
            - USER_OPS_INDEXER__DATABASE__CONNECT__URL=${USER_OPS_INDEXER__DATABASE__CONNECT__URL:-postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout}
            - USER_OPS_INDEXER__DATABASE__RUN_MIGRATIONS=true
        depends_on:
            - backend
        networks:
            - timefactory
        expose:
            - 8050
    # stats:
    #     image: ghcr.io/blockscout/stats
    #     container_name: stats
    #     pull_policy: always
    #     restart: always
    #     environment:
    #         - STATS__DB_URL=${STATS__DB_URL:-postgres://stats:n0uejXPl61ci6ldCuE2gQU5Y@stats-db:5432/stats}
    #         - STATS__BLOCKSCOUT_DB_URL=${STATS__BLOCKSCOUT_DB_URL:-postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout}
    #         - STATS__CREATE_DATABASE=${STATS__CREATE_DATABASE:-true}
    #         - STATS__RUN_MIGRATIONS=${STATS__RUN_MIGRATIONS:-true}
    #     depends_on:
    #         - backend
    #     networks:
    #         - timefactory
    #     expose:
    #         - 8050

networks:
    timefactory:
        external: true
volumes:
    blockscout:
        external: true
