services:
    backend:
        image: ghcr.io/blockscout/blockscout
        container_name: backend
        pull_policy: always
        restart: always
        stop_grace_period: 5m
        command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
        environment:
            - IPC_PATH=/.ethereum/geth.ipc
            - DATABASE_URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout?ssl=false
            - USER_OPS_INDEXER__DATABASE__CONNECT__URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout?ssl=false
            - REDIS_URL=redis://redis:6379/1
            - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
            - PORT=4000
        networks:
            - timefactory
        expose:
            - 4000
        volumes:
            - blockscout:/app/logs/
            - blockscout:/app/dets/
            - geth:/.ethereum

networks:
    timefactory:
        external: true
volumes:
    blockscout:
        external: true
    geth:
        external: true
