services:

sig-provider:
  container_name: sig-provider
  image: ghcr.io/blockscout/sig-provider
  pull_policy: always
  restart: always
  networks:
  - timefactory
  expose:
  - 8050

sc-verifier:
  image: ghcr.io/blockscout/smart-contract-verifier
  container_name: smart-contract-verifier
  pull_policy: always
  restart: always
  networks:
  - timefactory
  expose:
  - 8050
stats:
  image: ghcr.io/blockscout/stats
  container_name: stats
  pull_policy: always
  restart: always
  environment:
  - STATS__DB_URL=postgresql://postgres:${PASSWORD}@postgres:5432/stats
  - STATS__BLOCKSCOUT_DB_URL=postgresql://postgres:${PASSWORD}@postgres:5432/blockscout
  - STATS__CREATE_DATABASE=true
  - STATS__RUN_MIGRATIONS=true
  depends_on:
  - backend
  networks:
  - timefactory
  expose:
  - 8050
