services:
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        volumes:
            - pgadmin:/var/lib/pgadmin
        networks:
            - timefactory
        expose:
            - 80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
        labels:
            - traefik.enable=true
            - traefik.http.routers.pgadmin.rule=Host(`db.timefactory.io`)
            - traefik.http.routers.pgadmin.entrypoints=websecure
            - traefik.http.routers.pgadmin.tls=true
            - traefik.http.routers.pgadmin.tls.certresolver=cloudflare
            - traefik.http.services.pgadmin.loadbalancer.server.port=80
        restart: unless-stopped
        pull_policy: always
networks:
    timefactory:
        external: true

volumes:
    pgadmin:
        external: true
