services:
    actions:
        image: myoung34/github-runner
        container_name: actions
        environment:
            REPO_URL: https://github.com/zachklingbeil/factory
            RUNNER_NAME: actions
            RUNNER_TOKEN: ${TOKEN}
            RUNNER_WORKDIR: /runner/tmp/runner/work
            CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner # Required for persistence
            RUNNER_SCOPE: repo
            LABELS: linux,x64,gpu
            DISABLE_AUTOMATIC_DEREGISTRATION: true
        volumes:
            - actions:/runner # Use a single external volume
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - timefactory # Use external network
        restart: always
        pull_policy: always
volumes:
    actions:
        external: true

networks:
    timefactory:
        external: true
