services:
    ollama:
        container_name: ollama
        image: ollama/ollama
        volumes:
            - ollama:/root/.ollama
        networks:
            - timefactory
        expose:
            - 11434
        environment:
            - OLLAMA_KEEP_ALIVE=30m
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          count: all
        pull_policy: always
        restart: unless-stopped
    webui:
        container_name: webui
        image: ghcr.io/open-webui/open-webui:main
        volumes:
            - ollama:/app/backend/data
        networks:
            - timefactory
        expose:
            - 8080
        environment:
            - ENABLE_SIGNUP=false # ENABLE_SIGNUP=true required for the first account.
            - ENABLE_OLLAMA_API=true
            - OLLAMA_BASE_URL=http://ollama:11434
            - USE_CUDA_DOCKER=true
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          count: all
        pull_policy: always
        restart: unless-stopped

volumes:
    ollama:
        external: true
networks:
    timefactory:
        external: true
