services:
    postgres:
        container_name: postgres
        image: postgres:alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - timefactory
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${PASSWORD}
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: postgres
        command: ['postgres', '-c', 'max_wal_size=16GB']

        restart: unless-stopped
        pull_policy: always

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        volumes:
            - pgadmin:/var/lib/pgadmin
        networks:
            - timefactory
        expose:
            - 80
        environment:
            PGADMIN_DEFAULT_EMAIL: zach@zachklingbeil.com
            PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
        restart: unless-stopped
        pull_policy: always
networks:
    timefactory:
        external: true

volumes:
    postgres:
        external: true
    pgadmin:
        external: true
