services:
    postgres:
        container_name: postgres
        image: postgres:alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - timefactory
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        command:
            [
                'postgres',
                '-c',
                'max_wal_size=8GB',
                '-c',
                'max_connections=200',
                '-c',
                'client_connection_check_interval=60000',
            ]

        restart: unless-stopped
        pull_policy: always

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        volumes:
            - pgadmin:/var/lib/pgadmin
        networks:
            - timefactory
        expose:
            - 80
        environment:
            PGADMIN_DEFAULT_EMAIL: ${EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
        labels:
            - traefik.enable=true
            - traefik.http.routers.pgadmin.rule=Host(`db.timefactory.io`)
            - traefik.http.routers.pgadmin.entrypoints=websecure
            - traefik.http.routers.pgadmin.tls=true
            - traefik.http.routers.pgadmin.tls.certresolver=cloudflare
            - traefik.http.services.pgadmin.loadbalancer.server.port=80
        restart: unless-stopped
        pull_policy: always
networks:
    timefactory:
        external: true

volumes:
    postgres:
        external: true
    pgadmin:
        external: true
